### ISSUE TITLE
ETRI tokenizer 'prepare_for_model' 메소드 없음 오류

### ISSUE THREAD

**Issue by nugury55** [BM-K/KoSentenceBERT#2]
Transformer.py line 80에서 return self.tokenizer.prepare_for_model(tokens, max_length=pad_seq_length, padding='max_length', return_tensors='pt', truncation=True, prepend_batch_axis=True) 호출 시 오류가 발생합니다.
소스를 확인해 보니 최근에 받은 ETRI > KorBERT의 tokenizer > BertTokenizer 클래스에 prepare_for_model 메소드가 없습니다.
우회 할 수 있는 다른 방법이 있을까요?

**Comment by BM-K** [comment]
Transformer.py 부분이 정확히 어딘지 알려주실 수 있으신가요?

**Comment by nugury55** [comment]
확인 감사합니다~
아래 위치에 있는 소스이며, sentence_transformers 폴더를 site-packages에 복사해서 사용하고 있습니다
git master > /sentence_transformers/models/Transformer.py

**Comment by BM-K** [comment]
일단 확인해 보셔야 할 것은 다음과 같습니다.

1. 본 레파지토리에 있는 sentence_transformer, tokenizers, transformers 디렉토리가 site-packages에 잘 복사 되었는가

2. ETRI BERT Tokenizer eojeol을 사용하였는가

입니다.

tokenizer로 ETRI Tokenizer eojeol이 매핑 되어 있으면 tokenization_etri_eojeol > BertTokenizer 가 
transformers.tokenization_utils 의 PreTrainedTokenizer를 상속 받아 self.prepare_for_model을 사용할 수 있습니다. 
tokenizer가 잘 맵핑 되어 있는지 확인해볼 필요가 있습니다.

**Comment by bkmh** [comment]
저도 문의 주신 부분에서 막혀있는 상태에서, Owner분께 개인적으로 문의드렸던 부분이라 제가 경험했던 부분을 공유드립니다.
일단 Owner분께서 말씀해주신 대로 
**2. ETRI BERT Tokenizer eojeol을 사용하였는가** 
부분에서 아마도 최근 제공되고 있는 ETRI Tokenizer가 ETRI Tokenizer eojeol 과 다른 것 같습니다.

현재 제공되는 ETRI BERT내에 003_eojeol_pytorch/src_tokenizer/tokenization.py 만 존재하는 상황입니다.
해서 저도 위 답변처럼 기존 tokenization.py 내의 BertTokenizer를 transformers.tokenization_utils.PreTrainedTokenizer를 
상속받도록 소스를 수정했고, 해당 변경사항에 따라 
제공해주신 sentence_transformers 및 transformers 폴더 내의 일부 파일에 대해서 수정처리가 필요한 것 같습니다.

저는 결과 도출 측면에서만 접근해서, 오류나는 부분들을 되도록이면 주석처리하는 방식으로 진행했습니다.
일단 제가 수정한 부분은 transformers/tokenization_utils.py 중 오류나는 부분을 추가적으로 주석처리했습니다.

진행하시는데 도움이 되었으면 좋겠습니다.

**Comment by nugury55** [comment]
@BM-K, @bkmh  네 답변 감사합니다.
최신 ETRI BERT Tokenizer가 변경되었고 이에 따라 오류가 발생하는 것 같습니다. comment 주신 대로 확인해 보도록 하겠습니다.

**Comment by BM-K** [comment]
공개가 가능한 SKT KoBERT 모델을 활용하여 KorSBERT를 다음 레파지토리에 작성하였습니다. 
참고하셔도 좋을 것 같습니다.
https://github.com/BM-K/KoSentenceBERT_SKTBERT
