### ISSUE TITLE
tokenizer import 오류

### ISSUE THREAD

**Issue by qqq614** [BM-K/KoSentenceBERT#3]
안녕하세요~ 우선 좋은 코드 올려주셔서 감사하구요. 
우선 설명해주신대로 따라가고 있는데 sentence-transformer, transformers, tokenizers 폴더도 다 site-package로 옮겼구요. 
ETRI의 tokenizer 형태가 바뀜에 따라 다른 이슈에서 다른분이 설명하신 부분으로 PretrainedTokenizer 세팅까지는 되었는데요. tokenizers/\_\_init\_\_.py 에 있는 `from tokenizers import Tokenizer, Encoding, AddedToken` <- 여기서 에러가 나네요. 
주석처리하기에는 다른곳에서 쓰이고 잇어서 .ㅠㅠ

**Comment by BM-K** [comment]
https://hub.docker.com/r/klbm126/kosbert_image/tags

위 사이트에 있는 도커 이미지를 다운 받으셔서 한번 시도 해보세요.

**Comment by qqq614** [comment]
> https://hub.docker.com/r/klbm126/kosbert_image/tags
> 
> 위 사이트에 있는 도커 이미지를 다운 받으셔서 한번 시도 해보세요.

네 한번 해볼게요~
